/*
  fablabway.com
  file:        m08mkclient.sql
  project:     TAMISO - Oracle versioning/code-enh
  description: creates schema client 
  author:       Mauro Rossolato
  licence:      Creative Commons BY-NC-ND
  when        who   what
  -----------------------------------
  19.05.2016  mr    creates
*/

-- as sys

CREATE USER SELLCAR IDENTIFIED BY SELLCAR123
DEFAULT TABLESPACE BIGONE
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION,CONNECT TO SELLCAR;
GRANT RESOURCE TO SELLCAR;
GRANT CREATE ANY VIEW TO SELLCAR;
ALTER USER SELLCAR QUOTA UNLIMITED ON BIGONE;

GRANT EXECUTE ON TMSADM.TMSMAIN TO SELLCAR;
GRANT EXECUTE ON TMSADM.ENROLLER TO SELLCAR;
GRANT SELECT,INSERT,UPDATE ON TMSADM.M08DDLSRC TO SELLCAR;
GRANT SELECT,INSERT,UPDATE ON TMSADM.M08OBJCAT TO SELLCAR;
GRANT SELECT,INSERT,UPDATE ON TMSADM.M08OBJLCK TO SELLCAR;
GRANT SELECT,INSERT,UPDATE ON TMSADM.M08RELOBJ TO SELLCAR;
-- NO, GRANT SELECT ON DBA_HIST_SQLTEXT TO SELLCAR;

-- GRANT EXECUTE ON TMSADM.TMSMAIN TO MYAPEX;


