/*
  fablabway.com
  file:        m08mktmsadm.sql
  project:     TAMISO - Oracle versioning/code-enh
  description:  creates schema-repo
  author:       Mauro Rossolato
  licence:      Creative Commons BY-NC-ND
  when        who   what
  -----------------------------------
  19.05.2016  mr    creates
*/

-- RUN AS SYS

/* OPTIONAL, TABLESPACE "BIGONE" CREATION.
 
CREATE TABLESPACE BIGONE LOGGING DATAFILE 
  '/u01/app/oracle/oradata/XE/bigone_01.dbf' SIZE 100M  REUSE 
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K; 
*/

SET FEED ON ECHO ON VERIFY ON

CREATE USER TMSADM IDENTIFIED BY TMSADM123
	DEFAULT TABLESPACE BIGONE
	TEMPORARY TABLESPACE TEMP
/	


GRANT CONNECT TO TMSADM;
GRANT CREATE SESSION TO TMSADM;
GRANT RESOURCE TO TMSADM;
GRANT SELECT ON DBA_SOURCE TO TMSADM;
GRANT SELECT ON DBA_DIRECTORIES TO TMSADM;
GRANT SELECT ON DBA_OBJECTS TO TMSADM;
GRANT SELECT ON DBA_USERS TO TMSADM;
GRANT SELECT ON DBA_VIEWS TO TMSADM;
GRANT SELECT ON DBA_TRIGGERS TO TMSADM;
GRANT ADMINISTER DATABASE TRIGGER TO TMSADM;
GRANT SELECT_CATALOG_ROLE TO TMSADM;


ALTER USER TMSADM QUOTA UNLIMITED ON BIGONE
/

-- sudo mkdir /u01/app/oracle/oradata/kstdir
CREATE DIRECTORY KSTDIR AS '/u01/app/oracle/oradata/kstdir';


GRANT READ, WRITE ON DIRECTORY KSTDIR TO TMSADM;

GRANT EXECUTE ON SYS.DBMS_ADVISOR TO TMSADM;
GRANT ADVISOR TO TMSADM ;

GRANT SELECT ANY TABLE TO TMSADM;

GRANT SELECT ON DBA_HIST_SQLTEXT TO TMSADM;

-- CONN TMSADM/TMSADM123


