/*
  fablabway.com
  file:        m08mkproc.sql
  project:     TAMISO - Oracle versioning
  description: creates schema repository - proc
  author:       Mauro Rossolato
  licence:      Creative Commons BY-NC-ND
  when        who   what
  -----------------------------------
  19.05.2016  mr    creates
*/

--/////////////////////////////////////////////////////////////////////////////

CREATE OR REPLACE PROCEDURE ENROLLER(POBJNAME IN VARCHAR2,POWNER IN VARCHAR2,POBJTYPE IN VARCHAR2, PRETCODE OUT NUMBER, PRETMSG OUT VARCHAR2)
-- AUTHID DEFINER
 AUTHID CURRENT_USER
IS
WCNT NUMBER;
WNUM NUMBER;
WIDCAT NUMBER;
WCLOBTMP CLOB;
WNUMLINE NUMBER;
WOFFSET NUMBER;
WLENLOB NUMBER;
WROWLEN NUMBER;
WONEROW     VARCHAR2(32767);
WHASHDDL VARCHAR2(100);
WIDREL NUMBER;
WOBJTYPE VARCHAR2(100);
WTMSID VARCHAR2(60);
XNOTMSID EXCEPTION;
XNOLOCK EXCEPTION;
BEGIN

SELECT COUNT(*) INTO WCNT
FROM TMSADM.M08OBJCAT T1
WHERE 1=1
AND T1.MOWNER=POWNER
AND T1.MOBJNAME=POBJNAME
AND T1.MOBJTYPE=POBJTYPE;
IF WCNT > 0 THEN

--
SELECT COUNT(*) INTO WCNT
FROM TMSADM.M08OBJCAT T1,TMSADM.M08OBJLCK T2
WHERE 1=1
AND T1.ID_M08OBJCAT=T2.FK_M08OBJCAT
AND T1.MOWNER=POWNER
AND T1.MOBJNAME=POBJNAME
AND T1.MOBJTYPE=POBJTYPE
AND T2.MDATEUNLOCK IS NULL;

IF WCNT = 0 THEN
	RAISE XNOLOCK;
WNUM := 0;
END IF;

-- CHECKS IF OBJ HAS VALID TMSID
DBMS_APPLICATION_INFO.READ_CLIENT_INFO(WTMSID);

TMSADM.TMSMAIN.LOGEVT ('INFO','ENROLLER',NULL,'WTMSID='||WTMSID,NULL);


SELECT COUNT(*) INTO WCNT
FROM TMSADM.M08OBJLCK T2,TMSADM.M08OBJCAT T1
WHERE 1=1
AND T1.MTMSID=WTMSID
AND T1.ID_M08OBJCAT=T2.FK_M08OBJCAT
AND T2.MDATEUNLOCK IS NULL;

IF WCNT=0 THEN
RAISE XNOTMSID;
END IF;




DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'EMIT_SCHEMA',FALSE);		-- CURRENT SCHEMA
-- 12            DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_CREATION',FALSE);-- NO PHYSICAL INFO
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_ATTRIBUTES',FALSE);
            DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'PRETTY',TRUE);			-- BEAUTYFIER
            DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',FALSE);			--
/*
INSERT INTO M08OBJCAT (MOBJNAME, MOWNER, MOBJTYPE, MNUMROWS, MWHEN, MNOTE,MTMSID)
VALUES (POBJNAME,POWNER,POBJTYPE,0,SYSDATE,NULL,WTMSID)
returning id_M08OBJCAT into WIDCAT;
*/

SELECT ID_M08OBJCAT,MTMSID INTO WIDCAT,WTMSID
FROM TMSADM.M08OBJCAT T1
WHERE 1=1
AND T1.MOWNER=POWNER
AND T1.MOBJNAME=POBJNAME
AND T1.MOBJTYPE=POBJTYPE;

-- TMSADM.TMSMAIN.LOGEVT ('DEBUG',NULL,'IMPOSTATI WIDCAT,WTMSID',NULL);

WOBJTYPE := REPLACE(POBJTYPE,'PACKAGE BODY','PACKAGE_BODY');

-- TMSADM.TMSMAIN.LOGEVT ('DEBUG',NULL,'IMPOSTATI; '||WOBJTYPE||POBJNAME||POWNER,NULL);

        SELECT
            COUNT(*)
        INTO
            WCNT
        FROM
--            DBA_OBJECTS
USER_OBJECTS
        WHERE
            UPPER(OBJECT_NAME) = UPPER(POBJNAME)
--            AND   UPPER(OWNER) = UPPER(POWNER)
            AND   UPPER(OBJECT_TYPE) = UPPER(POBJTYPE);
IF WCNT=1 THEN
SELECT
    dbms_metadata.get_ddl(
    WOBJTYPE ,POBJNAME,POWNER) myrow
INTO
    wclobtmp
FROM
    dual;

SELECT ORA_HASH(wclobtmp) INTO WHASHDDL FROM DUAL;
TMSADM.TMSMAIN.LOGEVT ('DEBUG','ENROLLER',NULL,'HASH='||WHASHDDL,NULL);

INSERT INTO TMSADM.M08RELOBJ (MHASHDDL, FK_M08OBJCAT, MWHEN, MNUMROWS)
VALUES (WHASHDDL,WIDCAT,SYSDATE,NULL)
returning ID_M08RELOBJ into WIDREL;

            wlenlob := dbms_lob.getlength(wclobtmp);
            wnumline := 1;
            woffset :=0;
 --            INSERT INTO M08DDLSRC (FK_M08OBJCAT, MLINE, MTEXT) VALUES (WIDCAT,0,wonerow);
            WHILE woffset <= wlenlob LOOP
                wrowlen := instr(wclobtmp,chr(10),woffset) - woffset;
                IF
                    wrowlen < 0
                THEN
                    wrowlen := wlenlob + 1 - woffset;
                END IF;
                wonerow := nvl(substr(wclobtmp,woffset,wrowlen),'');
                IF LENGTH(LTRIM(RTRIM(wonerow)))>0 THEN
                INSERT INTO TMSADM.M08DDLSRC (FK_M08RELOBJ, MLINE, MTEXT) VALUES (WIDREL,wnumline,wonerow);
 --                               woffset := woffset + wrowlen + 1;
                wnumline := wnumline + 1;
                END IF;
                woffset := woffset + wrowlen + 1;
--                wnumline := wnumline + 1;

            END LOOP;
UPDATE TMSADM.M08RELOBJ SET MNUMROWS=wnumline
WHERE 1=1 AND ID_M08RELOBJ=WIDREL;
END IF;
-- COMMIT;
ELSE
TMSADM.TMSMAIN.LOGEVT ('WARN','ENROLLER',NULL,'new object added: '||POWNER||'.'||POBJNAME||' as '||POBJTYPE,NULL);
END IF;

EXCEPTION
  WHEN XNOTMSID THEN
  PRETCODE := 30018;
  PRETMSG := 'TMSERR: INVALID tmsid!';
TMSADM.TMSMAIN.LOGEVT ('ERROR','ENROLLER',NULL,'TMSERR: '||PRETMSG,NULL);
WHEN XNOLOCK THEN
  PRETCODE := 30022;
  PRETMSG := 'TMSERR: unable to LOCK obj!';
TMSADM.TMSMAIN.LOGEVT ('ERROR','ENROLLER',NULL,'TMSERR: '||PRETMSG,NULL);

WHEN OTHERS THEN
  PRETCODE := 39999;
  PRETMSG := 'TMSERR: '||SUBSTR(SQLERRM,1,200);
  TMSADM.TMSMAIN.LOGEVT ('ERROR','ENROLLER',NULL,'TMSERR: NOT defined error! '||'('||SUBSTR(SQLERRM,1,200)||')',NULL);

END;
/


--/////////////////////////////////////////////////////////////////////////////

