/*
  fablabway.com
  file:        m08yccatobj.sql
  project:     TAMISO - Oracle versioning
  description: add obj to catalog
  author:       Mauro Rossolato
  licence:      Creative Commons BY-NC-ND
  when        who   what
  -----------------------------------
  19.05.2016  mr    creates
*/


DECLARE 
WRETCODE NUMBER;
WRETMSG VARCHAR2(100);
BEGIN
TMSADM.TMSMAIN.CATOBJ('YCCARS','SELLCAR','TABLE' ,'YOUCAR' ,
'CARS MAIN LIST','YC001', WRETCODE , WRETMSG );
DBMS_OUTPUT.PUT_LINE(TO_CHAR(WRETCODE)||' - '||WRETMSG);
END;
/

DECLARE 
WRETCODE NUMBER;
WRETMSG VARCHAR2(100);
BEGIN
TMSADM.TMSMAIN.CATOBJ('YCCARPRO','SELLCAR','TABLE' ,'YOUCAR' ,
'CARS TEST ASSOC. TBL','YC001', WRETCODE , WRETMSG );
DBMS_OUTPUT.PUT_LINE(TO_CHAR(WRETCODE)||' - '||WRETMSG);
END;
/

DECLARE 
WRETCODE NUMBER;
WRETMSG VARCHAR2(100);
BEGIN
TMSADM.TMSMAIN.CATOBJ('YCPROSPECT','SELLCAR','TABLE' ,'YOUCAR' ,
'PROSPECT OR CUSTOMER','YC001', WRETCODE , WRETMSG );
DBMS_OUTPUT.PUT_LINE(TO_CHAR(WRETCODE)||' - '||WRETMSG);
END;
/

DECLARE 
WRETCODE NUMBER;
WRETMSG VARCHAR2(100);
BEGIN
TMSADM.TMSMAIN.CATOBJ('YCADDTEST','SELLCAR','PROCEDURE' ,'YOUCAR' ,
'ADDS PROSPECT FOR TEST DRIVE','YC001', WRETCODE , WRETMSG );
DBMS_OUTPUT.PUT_LINE(TO_CHAR(WRETCODE)||' - '||WRETMSG);
END;
/

DECLARE 
WRETCODE NUMBER;
WRETMSG VARCHAR2(100);
BEGIN
TMSADM.TMSMAIN.CATOBJ('YCCARTOSELL','SELLCAR','VIEW' ,'YOUCAR' ,
'LIST ON-SALE','YC001', WRETCODE , WRETMSG );
DBMS_OUTPUT.PUT_LINE(TO_CHAR(WRETCODE)||' - '||WRETMSG);
END;
/
